my_string=input('')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
my_string=my_string.strip( )
print(my_string)
print(my_string[0])
len(my_string)
print (my_string[-1])